export const paths = {
  login: '/login',
  company: {
    root: '/company',
    dashboard: '/company',
    routes: '/company/routes',
    trips: '/company/trips',
    bookings: '/company/bookings',
    bookingDetails: (bookingId: string) => `/company/bookings/${bookingId}`,
    tripArchive: '/company/trips/archive',
    tripSchedules: '/company/trips/schedules',
    tripNew: '/company/trips/new',
    tripDetails: (tripId: string) => `/company/trips/${tripId}`,
    tripDetailsBookings: (tripId: string) => `/company/trips/${tripId}?tab=bookings`,
    tripTracking: (tripId: string) => `/company/trips/${tripId}/tracking`,
    tripEdit: (tripId: string) => `/company/trips/${tripId}/edit`,
    vehicles: '/company/vehicles',
    drivers: '/company/drivers',
    promoCodes: '/company/promo-codes',
    promoCodeNew: '/company/promo-codes/new',
    promoCodeEdit: (promoId: string) => `/company/promo-codes/${promoId}/edit`,
    subscriptionPackages: '/company/subscription-packages',
    packageNew: '/company/subscription-packages/new',
    packageEdit: (packageId: string) => `/company/subscription-packages/${packageId}/edit`,
    packageSubscribers: (packageId: string) =>
      `/company/subscription-packages/${packageId}/subscribers`,
    complaints: '/company/complaints',
    complaintDetails: (complaintId: string) => `/company/complaints/${complaintId}`,
    notifications: '/company/notifications',
    settings: '/company/settings',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin',
    companies: '/admin/companies',
    companyNew: '/admin/companies/new',
    companyDetails: (companyId: string) => `/admin/companies/${companyId}`,
    users: '/admin/users',
    userDetails: (userId: string) => `/admin/users/${userId}`,
    vehicleModels: '/admin/vehicle-models',
    vehicleModelNew: '/admin/vehicle-models/new',
    vehicleModelEdit: (modelId: string) => `/admin/vehicle-models/${modelId}/edit`,
    cities: '/admin/cities',
    stations: '/admin/stations',
    restAreas: '/admin/rest-areas',
    promoCodes: '/admin/promo-codes',
    promoCodeNew: '/admin/promo-codes/new',
    promoCodeEdit: (promoId: string) => `/admin/promo-codes/${promoId}/edit`,
    platformPlans: '/admin/platform-plans',
    complaints: '/admin/complaints',
    complaintDetails: (complaintId: string) => `/admin/complaints/${complaintId}`,
    complaintCategories: '/admin/complaint-categories',
    notifications: '/admin/notifications',
    settings: '/admin/settings',
  },
} as const
